### ISSUE TITLE
regression on last version

### ISSUE THREAD

**Issue by cyrilleTixierLefebreDalloz** [okorach/sonarqube-tools#195]
Hello
after reinstall, i got an issue i didnt have before :
2021-11-17 19:13:26,331 | sonarqube-tools | CRITICAL | HTTP fatal error 404 - 404 Client Error: for url: http://MySonarUrl/api/project_dump/export?key=myProjectGroup%3AMyProjectArtifact
404 Client Error: for url: http://MySonarUrl/api/project_dump/export?key=myProjectGroup%3AMyProjectArtifact
the project with 404 is a project with no line in master branch but have lines in a develop branch. 
I didn't have this error before the fix for the issue

**Comment by okorach** [comment]
Hello @cyrilleTixierLefebreDalloz,
On which of the tools (commands) do you have this regression ?
The fix for issue #191 on **sonar-tools** 1.4.7 was a very surgical change in **sonar-measures-export** that does not use `api/project_dump/export` so I am a bit surprised. This could be another bug, but I don't see how it can be a regression over sonar-tools 1.4.6

**Comment by cyrilleTixierLefebreDalloz** [comment]
make some mistake : 
i got the problem on sonar-projects-export
i didn't updted well the project. with the update, my previous ticket is fixed and this error still occurs.
i use sonar 8.9.1 in developer edition.
=> this issue can be closed.
